<?php

// Paths to configuration files
$config_file = __DIR__ . '/../includes/config.php';
$default_config_file = __DIR__ . '/../includes/default-config.php';

// Check if config.php exists; if so, exit the script
if (file_exists($config_file)) {
    die("<h3>Config.php already exists. Setup is not required. For security, please delete the setup/ directory.</h3>");
}

// Check if default-config.php exists; if not, exit the script
if (!file_exists($default_config_file)) {
    die("<h3>Error: default-config.php does not exist!</h3>");
}

// Include default configuration values
include($default_config_file);

// Process form submission
if ($_SERVER['REQUEST_METHOD'] === 'POST') {

    // Build the content for config.php
    $config_content = "<?php\n";
    $config_content .= "// Auto-generated by setup script\n\n";

    foreach ($_POST as $key => $value) {
        if ($key === 'server_port') {
            $escaped_value = (int)$value;
            $config_content .= "$" . "$key = $escaped_value;\n";
        } else {
            $escaped_value = addslashes($value);
            $config_content .= "$" . "$key = \"$escaped_value\";\n";
        }
    }

    $config_content .= "\n?>";

    // Provide config.php content as a downloadable file
    header('Content-Type: text/plain');
    header('Content-Disposition: attachment; filename="config.php"');
    echo $config_content;
    exit;
}

?>

<!DOCTYPE html>
<html>
<head>
    <title>Website Setup</title>
    <style>
        body { font-family: Arial, sans-serif; background-color: #f5f5f5; padding: 20px; }
        form { max-width: 600px; margin: auto; background: #fff; padding: 20px; border-radius: 5px; box-shadow: 0 2px 4px rgba(0,0,0,0.1); }
        label { font-weight: bold; }
        input[type="text"] { width: 100%; padding: 8px; margin-bottom: 15px; border-radius: 3px; border: 1px solid #ccc; }
        input[type="submit"] { padding: 10px 20px; background: #4CAF50; color: #fff; border: none; border-radius: 3px; cursor: pointer; }
        .instructions { max-width: 600px; margin: auto; padding: 10px; background-color: #fffae6; border: 1px solid #ffd700; border-radius: 5px; margin-bottom: 20px; }
    </style>
</head>
<body>

<div class="instructions">
    <h3>Setup Instructions</h3>
    <p>We have found <strong>default-config.php</strong>. This setup script helps you generate a new <strong>config.php</strong> for your website. After downloading, use your FTP client to place <strong>config.php</strong> into the <strong>includes/</strong> folder, and then remove the <strong>setup/</strong> directory from your server for security purposes.</p>
</div>

<form method="post">
    <h2>Website Configuration</h2>

    <?php
    // Generate form fields based on default-config.php variables
    $default_vars = get_defined_vars();

    foreach ($default_vars as $var_name => $var_value) {
        if (is_string($var_value) || is_int($var_value)) {
            echo "<label>" . htmlspecialchars($var_name) . "</label>";
            echo "<input type='text' name='" . htmlspecialchars($var_name) . "' value='" . htmlspecialchars($var_value) . "'>";
        }
    }
    ?>

    <p><strong>Reminder:</strong> Pressing submit will download the generated <strong>config.php</strong>. Remember to upload it into your <strong>includes/</strong> folder and remove the <strong>setup/</strong> directory afterward.</p>

    <input type="submit" value="Generate and Download config.php">
</form>

</body>
</html>
